name: DASH-docker-saithrift-bldr-image

on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-saithrift-bldr-docker.yml'
      - 'dash-pipeline/Makefile'
      - 'dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr'
      - 'dash-pipeline/dockerfiles/DOCKER_SAITHRIFT_BLDR_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-saithrift-bldr-docker.yml'
      - 'dash-pipeline/Makefile'
      - 'dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr'
      - 'dash-pipeline/dockerfiles/DOCKER_SAITHRIFT_BLDR_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build dash-saithrift-bldr-image
    runs-on: ubuntu-20.04
    env:
      docker_fg_flags: -u root --privileged
      docker_bg_flags: -d -u root --privileged
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build docker-saithrift-bldr image
      run:  make docker-saithrift-bldr
