name: DASH-docker-p4c-bmv2-build-publish-acr


on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-p4c-bmv2-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.p4c-bmv2'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-p4c-bmv2-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.p4c-bmv2'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build docker dash-p4c-bmv2 image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-p4c-bmv2 docker image
      run: make docker-dash-p4c
    - name: Publish dash-p4c-bmv2 docker image
      run: make docker-publish-dash-p4c
