name: DASH-docker-p4c-bmv2-build-publish-acr

on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-p4c-bmv2-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.p4c-bmv2'
      - 'dash-pipeline/dockerfiles/DOCKER_P4C_BMV2_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-p4c-bmv2-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.p4c-bmv2'
      - 'dash-pipeline/dockerfiles/DOCKER_P4C_BMV2_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish docker dash-p4c-bmv2 image
    # Can only publish from within DASH repo (need credentials from secrets)
    if: github.repository == 'Azure/DASH'
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-p4c-bmv2 docker image
      run: make docker-dash-p4c
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DASH_ACR_LOGIN_SERVER }}
        username: ${{ secrets.DASH_ACR_USERNAME }}
        password: ${{ secrets.DASH_ACR_PASSWORD }}    
    - name: Publish dash-p4c-bmv2 docker image to ACR
      run: make docker-publish-dash-p4c
