name: DASH-docker-bmv2-bldr-build-image


on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build docker dash-bmv2-bldr image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-bmv2-bldr docker image
      run: make docker-bmv2-bldr
